name: Wake ban sync bot

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Fly deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.FLY_API_TOKEN }}" \
            https://api.fly.io/apps/luminue-helper/machines
